### ISSUE TITLE
Spring 4.2.4 and Tomcat WebSocket faillure

### ISSUE THREAD

**Issue by emorakis** [rstoyanchev/spring-websocket-portfolio#62]
Hi everyone i would like to start by apologising if this is the wrong place to ask the following question. I have been strugling with a webapp using spring 4.2.4 and tomcat (both versions 7.0.47 and 8.0.32) that uses spring's support for stomp/websocket utilizing the sockjs stuff. I have moddeled my dispatcher-xml per your design here: [https://github.com/spring-projects/spring-framework/blob/master/spring-websocket/src/test/resources/org/springframework/web/socket/config/websocket-config-handlers-sockjs-attributes.xml](url)

and also the guidelines of spring listed here:<http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html>
I started out originally **with this** configuration that utilises a full message broker (not the simple memory one) inside my **dispatcher-servlet.xml**:       

   ```
<websocket:message-broker application-destination-prefix="/app">
           <websocket:stomp-endpoint path="/stomp">
              <websocket:sockjs/>
           </websocket:stomp-endpoint>
           <websocket:stomp-broker-relay prefix="/topic,/queue"
               relay-host="localhost" relay-port="61613"
               heartbeat-send-interval="20000" heartbeat-receive-interval="21000"
               client-login="my-client" client-passcode="aesdf"
               system-login="syslogin" system-passcode="qwrt"/>
           <websocket:client-inbound-channel>
    			<websocket:executor core-pool-size="30" max-pool-size="60" keep-alive-seconds="300"/>
    	   </websocket:client-inbound-channel>
    	   <websocket:client-outbound-channel>
    			<websocket:executor core-pool-size="31" max-pool-size="61" keep-alive-seconds="301"/>
    	   </websocket:client-outbound-channel>
    	   <websocket:broker-channel>
    			<websocket:executor core-pool-size="32" max-pool-size="62" keep-alive-seconds="302"/>
    		</websocket:broker-channel>	
    </websocket:message-broker>  
```

when tried this originally with **tomcat 7.0.47** i got the following stack-trace:

    INFO: Initializing Spring FrameworkServlet 'dispatcher' WARN | Failed to create a default WebSocketTransportHandler
        java.lang.IllegalStateException: No suitable default RequestUpgradeStrategy found
        	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.initRequestUpgradeStrategy(AbstractHandshakeHandler.java:145)
        	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.<init>(AbstractHandshakeHandler.java:111)
        	at org.springframework.web.socket.server.support.DefaultHandshakeHandler.<init>(DefaultHandshakeHandler.java:35)
        	at org.springframework.web.socket.sockjs.transport.handler.DefaultSockJsService.getDefaultTransportHandlers(DefaultSockJsService.java:91)
        	at org.springframework.web.socket.sockjs.transport.handler.DefaultSockJsService.<init>(DefaultSockJsService.java:53)
        	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:634)
        	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:407)
        	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
        	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
        	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
        	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
        	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
        	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        	at javax.servlet.GenericServlet.init(GenericServlet.java:212)
        	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173)
        	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
        	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4350)
        	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4659)
        	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
        	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
        	at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        	at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMojo.java:558)
        	at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java:255)
        	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.lang.reflect.Method.invoke(Method.java:606)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

which i guess the important stuff show up in the beginnig complaining about not being able to create a **WebSocketTransportHandler** due to no suitable **default RequestUpgradeStrategy** . Upgrading tomcat to version 8.0.32 gave the exact same result.  

I then thought i could change the dispatcher-servle.xml code to contain a transport like so to solve the problem: 

     <websocket:message-broker application-destination-prefix="/app">
           <websocket:stomp-endpoint path="/stomp">
                <websocket:sockjs websocket-enabled="false">
                	<websocket:transport-handlers register-defaults="true">
                		<ref bean="webSocketTransportHandler"/>
                	</websocket:transport-handlers>
                </websocket:sockjs>
           </websocket:stomp-endpoint>
           <websocket:stomp-broker-relay prefix="/topic,/queue"
               relay-host="localhost" relay-port="61613"
               heartbeat-send-interval="20000" heartbeat-receive-interval="21000"
               client-login="my-client" client-passcode="aesdf"
               system-login="syslogin" system-passcode="qwrt"/>
           <websocket:client-inbound-channel>
    			<websocket:executor core-pool-size="300" max-pool-size="600" keep-alive-seconds="300"/>
    	   </websocket:client-inbound-channel>
    	   <websocket:client-outbound-channel>
    			<websocket:executor core-pool-size="301" max-pool-size="601" keep-alive-seconds="301"/>
    	   </websocket:client-outbound-channel>
    	   <websocket:broker-channel>
    			<websocket:executor core-pool-size="302" max-pool-size="602" keep-alive-seconds="302"/>
    		</websocket:broker-channel>	
    	</websocket:message-broker>
    	
    	
    	<bean id="defaultHandshakeHandler" class="org.springframework.web.socket.server.support.DefaultHandshakeHandler">
    		 <constructor-arg ref="tomcatUpgradeStrategy"/>
    	</bean>
    	
    	<bean id="webSocketTransportHandler" class="org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler">
    		 <constructor-arg ref="defaultHandshakeHandler"/>
    	</bean>
    
    	<bean id="tomcatUpgradeStrategy" class="org.springframework.web.socket.server.standard.TomcatRequestUpgradeStrategy"/>
  which then reported the following stack-trace in both versions of tomcat (i.e. 7.0.47 and 8.0.32):

    INFO: Initializing Spring FrameworkServlet 'dispatcher'
     WARN | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.socket.server.support.WebSocketHandlerMapping#0': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/websocket/WebSocketContainer
    ERROR | Context initialization failed
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.socket.server.support.WebSocketHandlerMapping#0': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/websocket/WebSocketContainer
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
    	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
    	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
    	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
    	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
    	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
    	at javax.servlet.GenericServlet.init(GenericServlet.java:212)
    	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173)
    	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
    	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4350)
    	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4659)
    	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
    	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
    	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
    	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
    	at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
    	at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMojo.java:558)
    	at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java:255)
    	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: java.lang.NoClassDefFoundError: javax/websocket/WebSocketContainer
    	at java.lang.Class.getDeclaredMethods0(Native Method)
    	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
    	at java.lang.Class.getDeclaredMethods(Class.java:1868)
    	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:609)  

**and some more truncated from the above trace to conserve space...**

basically this time complaining it cannot create bean **org.springframework.web.socket.server.support.WebSocketHandlerMapping#0'** due to initialization erros because of class: **javax/websocket/WebSocketContainer** not being found.However this class is in the project's class path since i can see it is being included with tomcat's libraries. I know that is a lot to ask but can someone please explain what is going on with spring and tomcat and the websockets thing cause i am really running late with work because of this issue that i cannot seem to resolve.  
For completness i also include the **pom** for the project:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.dynamic-list</groupId>
      <artifactId>DynamicList</artifactId>
      <packaging>war</packaging>
      <version>0.0.1-SNAPSHOT</version>
      <name>DynamicList Maven Webapp</name>
      <url>http://maven.apache.org</url>
      <properties>
    		<spring.version>4.2.4.RELEASE</spring.version>
      </properties>
      <dependencies>
        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>3.8.1</version>
          <scope>test</scope>
        </dependency>
        <dependency>
        	<groupId>javax.servlet</groupId>
        	<artifactId>jstl</artifactId>
        	<version>1.2</version>
    	</dependency>
        <dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-core</artifactId>
    			<version>${spring.version}</version>
    		</dependency>
     
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-web</artifactId>
    			<version>${spring.version}</version>
    		</dependency>
     
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-webmvc</artifactId>
    			<version>${spring.version}</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-messaging</artifactId>
    			<version>${spring.version}</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>org.springframework.webflow</groupId>
    			<artifactId>spring-webflow</artifactId>
    			<version>2.4.2.RELEASE</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>org.glassfish</groupId>
    			<artifactId>javax.json</artifactId>
    			<version>1.0.4</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>com.fasterxml.jackson.core</groupId>
    			<artifactId>jackson-core</artifactId>
    			<version>2.7.1</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>com.fasterxml.jackson.core</groupId>
    			<artifactId>jackson-annotations</artifactId>
    			<version>2.7.1</version>
    		</dependency>
    		
    		<dependency>
        		<groupId>com.fasterxml.jackson.core</groupId>
        		<artifactId>jackson-databind</artifactId>
        		<version>2.7.1-1</version>
    		</dependency>
    				
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-websocket</artifactId>
    			<version>4.2.4.RELEASE</version>
    		</dependency>
      		<dependency>
    			<groupId>org.projectreactor</groupId>
    			<artifactId>reactor-core</artifactId>
    			<version>1.0.0.RELEASE</version>
    		</dependency>
    		
    		<dependency>
    			<groupId>org.apache.activemq</groupId>
    			<artifactId>activemq-all</artifactId>
    			<version>5.13.1</version>
    		</dependency>
    				
    		
      </dependencies>
      <build>
        <finalName>DynamicList</finalName>
      </build>
    </project>

**Comment by emorakis** [comment]
Please disregard the oppened issue. It was infact caused by a misconfigured maven plugin in eclipse in combination with some missing dependencies regarding the reactor project and not the actual websocket/sockjs xml configuration. Apologies for any inconvinience caused.
